### ISSUE TITLE
Cleanup code tree

### ISSUE THREAD

**Issue by daar** [mickadam/PinholeCalculator#13]
Remove the following folders, unless they belong to the project in some way
- ADK_test_Led
- AndroidEchoClient
- FirstTestADK
- JavaChatServer

Move the files from the folder 'PinHoleCalculator' one level down and remove the folder where they were in.

**Comment by mickadam** [comment]
test

**Comment by daar** [comment]
I have just pulled the master branch and got this error: Project 'PinHoleCalculator' is missing required source folder: 'gen'.

**Comment by mickadam** [comment]
ok thanks, i will check that as soon as possible

**Comment by mickadam** [comment]
Gen folder pushed on master. It is not necessary to have it on github, because it's generated ( In my case with eclipse + ADK), but if you need it.
